//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightScheduleDetection.DataAccess.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightsScheduleDBContext : DbContext
    {
        public FlightsScheduleDBContext()
            : base("name=FlightsScheduleDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flight> flights { get; set; }
        public virtual DbSet<route> routes { get; set; }
        public virtual DbSet<subscription> subscriptions { get; set; }
    }
}
