//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightScheduleDetection.DataAccess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public int agency_id { get; set; }
        public int origin_city_id { get; set; }
        public int destination_city_id { get; set; }
    }
}
